name: flutter_skeleton
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.7.2

dependencies:
  google_fonts: ^6.2.1
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  # Firebase dependencies (REMOVE THESE):
  # firebase_core: ^3.13.1
  # firebase_auth: ^5.1.0
  # cloud_firestore: ^5.0.0
  # firebase_storage: ^12.4.6

  # Supabase dependencies (ADD THESE):
  supabase_flutter: ^2.5.0 # Use the latest stable version

  image_picker: ^1.1.2 # Keep image_picker for selecting images

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/beach.jpg
    - assets/images/beach bbq.jpg
    - assets/images/breakfast.jpg
    - assets/images/coupons 50 points.jpeg
    - assets/images/free parking 10 points.jpg
    - assets/images/logo.png
    - assets/images/new member point 50.jpeg
    - assets/images/profile.jpg
    - assets/images/rate.jpeg
    - assets/images/slush.jpg
    - assets/images/suite.jpeg
    - assets/images/voucher 100 points.jpeg
