name: flutter_skeleton
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.7.2

dependencies:
  google_fonts: ^6.2.1
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8


  # Supabase dependencies:
  supabase_flutter: ^2.5.0 # Use the latest stable version

  image_picker: ^1.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  flutter_launcher_icons: ^0.13.1

# Configuration for flutter_launcher_icons
flutter_launcher_icons:
  android: "launcher_icon" # Or your preferred icon name
  ios: true
  image_path: "assets/images/logo.png" # Make sure this path is correct for your logo image
  min_sdk_android: 21 # Set to your project's minSdk (usually 21 or higher)
  remove_alpha_ios: true # Recommended for iOS if your logo has transparency

flutter:
  uses-material-design: true
  assets:
    - assets/images/beach.jpg
    - assets/images/beach bbq.jpg
    - assets/images/breakfast.jpg
    - assets/images/coupons 50 points.jpeg
    - assets/images/free parking 10 points.jpg
    - assets/images/logo.png # Ensure this is the correct path to your logo for the app icon
    - assets/images/new member point 50.jpeg
    - assets/images/profile.jpg
    - assets/images/rate.jpeg
    - assets/images/slush.jpg
    - assets/images/suite.jpeg
    - assets/images/voucher 100 points.jpeg